### ISSUE TITLE
Client Class

### ISSUE THREAD

**Issue by Jack-Fraser16** [fhir-crucible/testscript-engine#66]
**Is your feature request related to a problem? Please describe.**
Create a client class to keep track of the different clients needed for a runnable. Additionally, the client class should have some sort of support for one-off requests (i.e. profile loading) where creating and maintaining the client is not important.

**Comment by jhlee-mitre** [comment]
Merge the issue with https://github.com/fhir-crucible/testscript-engine/issues/53 and close.
